### ISSUE TITLE
styling per series

### ISSUE THREAD

**Issue by githubblock** [Kozea/pygal#114]
Very impressed with pygal.

One thing I found myself wishing though was for a way to set styling per series instead of only being able to set global chart styling. The global styling works great for a small number of series, but I’ve been finding charts difficult to read with more than that. 

For instance, I’d love to be able to have one series use fill, another a solid line, and a third using just dots.   Attached is a capture illustrating the type of graph I'm dreaming about. 

Am I correct that this would be impossible out of the box? (ignore the dashed-line style and major/minor guide styles)

![seriesstyle](https://cloud.githubusercontent.com/assets/7133394/2594928/f82ae97e-ba93-11e3-8ae1-83731f5c10d0.png)

**Comment by paradoxxxzero** [comment]
http://www.pygal.org/en/latest/documentation/configuration/serie.html
