### ISSUE TITLE
StackedBar Chart Legend vs stacking confusing

### ISSUE THREAD

**Issue by cleder** [Kozea/pygal#141]
![pygal-stacked-bar](https://cloud.githubusercontent.com/assets/1218010/3720221/067db83a-1651-11e4-9354-500e82d018fe.png)

The topmost value in the legend is the bottommost in the graph and vice versa. The occurence in the legend should match the chart.

**Comment by sergedroz** [comment]
Sorry to reopen this. Could a similar mechanism implemented for Horizontal Bars, so that the order in the legend is the same as in the bars.

**Comment by muchovej** [comment]
I second sergedroz's request.  Is there any way to implement this for Horizontal Bars?

**Comment by paradoxxxzero** [comment]
Isn't this fixed by https://github.com/Kozea/pygal/issues/229 ?

**Comment by muchovej** [comment]
Hello--

Thanks!  That seems to be part of the fix.  The problem I keep seeing now
is that there is a large blank space at the bottom of the plot (see
attached image).  Do you know what could be causing this?  Thanks so much
for all your help, I'm really enjoying pygal and thank you for making it
available.

peace,
sjcm
