### ISSUE TITLE
FR: set individual bar/dot color

### ISSUE THREAD

**Issue by funkyfuture** [Kozea/pygal#159]
I'd like to set individual colors to the bars or dots of a series.

This may be done automatically on those which are highlighted with ```x_labels_major``` in conjunction with the theme.

Or individually by providing a series of colors.

Any further thoughts on that?

**Comment by h-2-0** [comment]
I concur. I think it would be a great idea.

**Comment by paradoxxxzero** [comment]
This is now possible using metadata.
