### ISSUE TITLE
Can view svg in Inkscape but not in browser

### ISSUE THREAD

**Issue by bjayaram** [Kozea/pygal#164]
I am running pygal on a Mac running Mavericks and the svg generated can be opened in Inkscape but I am getting a blank page in Chrome or Safari. It is not a SVG issue but something simple in perhaps js that I am unable to figure it out. Appreciate any help.

Thanks,
Jayaram

<-----------------HTML file with svg image------------------>

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html>
	<head>
		<script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"/>
		<script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/pygal-tooltips.js"/>
		
	</head>
	<body>
		<figure>
			
			<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="pygal-chart" id="chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf" viewBox="0 0 800 600">
				
				
				
				<defs>
					<style type="text/css">#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .title{font-family:"monospace";font-size:16px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .legends .legend text{font-family:"monospace";font-size:14px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis text{font-family:"monospace";font-size:10px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis text.major{font-family:"monospace";font-size:10px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .series text{font-family:"monospace";font-size:8px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .tooltip text{font-family:"monospace";font-size:16px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf text.no_data{font-size:64px}
#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf{background-color:black}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf path,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf rect,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf circle{-webkit-transition:250ms;-moz-transition:250ms;transition:250ms}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .graph &gt; .background{fill:black}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .plot &gt; .background{fill:#111}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .graph{fill:#999}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf text.no_data{fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .title{fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .legends .legend text{fill:#999}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .legends .legend:hover text{fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .line{stroke:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .guide.line{stroke:#555}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .major.line{stroke:#999}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis text.major{stroke:#eee;fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y .guides:hover .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .line-graph .axis.x .guides:hover .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .stackedline-graph .axis.x .guides:hover .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .xy-graph .axis.x .guides:hover .guide.line{stroke:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .guides:hover text{fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .reactive{fill-opacity:.8}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .reactive.active,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .active .reactive{fill-opacity:.4}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .series text{fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .tooltip rect{fill:#111;stroke:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .tooltip text{fill:#eee}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .map-element{fill:#999;stroke:#555 !important;opacity:.9;stroke-width:3;-webkit-transition:250ms;-moz-transition:250ms;-o-transition:250ms;transition:250ms}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .map-element:hover{opacity:1;stroke-width:10}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-0,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-0 a:visited{stroke:#ff5995;fill:#ff5995}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-1,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-1 a:visited{stroke:#b6e354;fill:#b6e354}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-2,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-2 a:visited{stroke:#feed6c;fill:#feed6c}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-3,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-3 a:visited{stroke:#8cedff;fill:#8cedff}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-4,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-4 a:visited{stroke:#9e6ffe;fill:#9e6ffe}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-5,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-5 a:visited{stroke:#899ca1;fill:#899ca1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-6,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-6 a:visited{stroke:#f8f8f2;fill:#f8f8f2}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-7,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-7 a:visited{stroke:#bf4646;fill:#bf4646}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-8,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-8 a:visited{stroke:#516083;fill:#516083}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-9,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-9 a:visited{stroke:#f92672;fill:#f92672}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-10,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-10 a:visited{stroke:#82b414;fill:#82b414}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-11,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-11 a:visited{stroke:#fd971f;fill:#fd971f}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-12,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-12 a:visited{stroke:#56c2d6;fill:#56c2d6}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-13,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-13 a:visited{stroke:#808384;fill:#808384}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-14,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-14 a:visited{stroke:#8c54fe;fill:#8c54fe}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-15,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .color-15 a:visited{stroke:#465457;fill:#465457}
#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf text.no_data{text-anchor:middle}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .guide.line{fill-opacity:0}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .centered{text-anchor:middle}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .title{text-anchor:middle}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .legends .legend text{fill-opacity:1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.x text{text-anchor:middle}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.x:not(.web) text[transform]{text-anchor:start}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y text{text-anchor:end}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y2 text{text-anchor:start}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y .logarithmic text:not(.major),#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y2 .logarithmic text:not(.major){font-size:50%}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .guide.line{stroke-dasharray:4,4}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .major.guide.line{stroke-dasharray:6,6}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis text.major{stroke-width:0.5px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .horizontal .axis.y .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .horizontal .axis.y2 .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .vertical .axis.x .guide.line{opacity:0}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .horizontal .axis.always_show .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .vertical .axis.always_show .guide.line{opacity:1 !important}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y .guides:hover .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.y2 .guides:hover .guide.line,#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis.x .guides:hover .guide.line{opacity:1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .axis .guides:hover text{opacity:1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .nofill{fill:none}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .subtle-fill{fill-opacity:.2}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .dot{stroke-width:1px;fill-opacity:1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .dot.active{stroke-width:5px}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .series text{stroke:none}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .series text.active{opacity:1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .tooltip rect{fill-opacity:0.8}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .tooltip text{fill-opacity:1}#chart-491ef0f1-4c5f-46cd-857a-3130ced1caaf .tooltip text tspan.label{fill-opacity:.8}</style>
					<script type="text/javascript">window.config = {"inner_radius": 0, "print_values": true, "tooltip_font_size": 16, "y_title": null, "y_labels_major": null, "height": 600, "legend_at_bottom": false, "show_legend": true, "show_dots": true, "explicit_size": false, "legend_font_size": 14, "x_labels_major_count": null, "major_label_font_size": 10, "fill": false, "half_pie": false, "style": {"opacity": ".8", "foreground": "#999", "plot_background": "#111", "foreground_light": "#eee", "transition": "250ms", "foreground_dark": "#555", "opacity_hover": ".4", "colors": ["#ff5995", "#b6e354", "#feed6c", "#8cedff", "#9e6ffe", "#899ca1", "#f8f8f2", "#bf4646", "#516083", "#f92672", "#82b414", "#fd971f", "#56c2d6", "#808384", "#8c54fe", "#465457"], "background": "black", "font_family": "monospace"}, "x_title": null, "zero": 0, "show_minor_x_labels": true, "interpolation_parameters": {}, "x_labels_major": null, "rounded_bars": null, "label_font_size": 10, "show_y_labels": true, "dots_size": 2.5, "show_y_guides": true, "show_minor_y_labels": true, "x_labels": null, "value_font_size": 8, "x_label_rotation": 0, "disable_xml_declaration": false, "strict": false, "css": ["style.css", "graph.css"], "title_font_size": 16, "show_only_major_dots": false, "human_readable": false, "show_x_guides": false, "spacing": 10, "y_label_rotation": 0, "pretty_print": false, "tooltip_border_radius": 0, "interpolate": null, "js": ["http://kozea.github.com/pygal.js/javascripts/svg.jquery.js", "http://kozea.github.com/pygal.js/javascripts/pygal-tooltips.js"], "y_labels": null, "y_labels_major_every": null, "interpolation_precision": 250, "value_formatter": null, "no_data_font_size": 64, "logarithmic": false, "width": 800, "print_zeroes": false, "no_data_text": "No data", "truncate_legend": null, "x_labels_major_every": null, "title": "Candidate's work experience (in number of months)", "legend_box_size": 12, "no_prefix": false, "stroke": true, "include_x_axis": false, "range": null, "truncate_label": null, "order_min": null, "mode": null, "y_labels_major_count": null, "x_label_format": "%Y-%m-%d %H:%M:%S.%f", "margin": 20, "stack_from_top": false}</script>
					<script type="text/javascript" xlink:href="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"/>
					<script type="text/javascript" xlink:href="http://kozea.github.com/pygal.js/javascripts/pygal-tooltips.js"/>
				</defs>
				<title>Candidate's work experience (in number of months)</title>
				<g class="graph pie-graph vertical">
					<rect class="background" height="600" width="800" x="0" y="0"/>
					<g class="plot" transform="translate(168, 46)">
						<rect class="background" height="534" width="612.0" x="0" y="0"/>
						<g class="series serie-0 color-0">
							<g class="slices">
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M306.000000 0.000000 A267.000000 267.000000 0 0 1 365.622434 6.742118 L359.660190 32.767906 A240.300000 240.300000 0 0 0 306.000000 26.700000 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">334.501150922</desc>
									<desc class="y centered">14.9563393058</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M365.622434 6.742118 A267.000000 267.000000 0 0 1 422.233771 26.627975 L410.610394 50.665177 A240.300000 240.300000 0 0 0 359.660190 32.767906 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">390.064066179</desc>
									<desc class="y centered">27.6852380702</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M422.233771 26.627975 A267.000000 267.000000 0 0 1 515.283497 101.200670 L494.355147 117.780603 A240.300000 240.300000 0 0 0 410.610394 50.665177 z"/>
									<desc class="value">7.17%</desc>
									<desc class="x centered">464.626232875</desc>
									<desc class="y centered">69.070616775</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M515.283497 101.200670 A267.000000 267.000000 0 0 1 572.995768 268.503227 L546.296191 268.352905 A240.300000 240.300000 0 0 0 494.355147 117.780603 z"/>
									<desc class="value">10.75%</desc>
									<desc class="x centered">545.784255169</desc>
									<desc class="y centered">184.284623721</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M572.995768 268.503227 A267.000000 267.000000 0 0 1 565.918079 328.086758 L539.926272 321.978082 A240.300000 240.300000 0 0 0 546.296191 268.352905 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">557.879202748</desc>
									<desc class="y centered">296.919721305</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M565.918079 328.086758 A267.000000 267.000000 0 0 1 530.983371 410.775807 L508.485034 396.398226 A240.300000 240.300000 0 0 0 539.926272 321.978082 z"/>
									<desc class="value">5.38%</desc>
									<desc class="x centered">539.653120776</desc>
									<desc class="y centered">365.714445001</desc>
								</g>
								<g class="big_slice">
									<path class="slice reactive tooltip-trigger" d="M306.000000 26.700000 A240.300000 240.300000 0 0 1 508.485034 396.398226 L306.000000 267.000000 A0.000000 0.000000 0 0 0 306.000000 267.000000 z"/>
									<desc class="value">34.05%</desc>
									<desc class="x centered">411.379364566</desc>
									<desc class="y centered">209.283347086</desc>
								</g>
							</g>
						</g>
						<g class="series serie-1 color-1">
							<g class="slices">
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">519.734202562</desc>
									<desc class="y centered">403.587016788</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">519.734202562</desc>
									<desc class="y centered">403.587016788</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">519.734202562</desc>
									<desc class="y centered">403.587016788</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M530.983371 410.775807 A267.000000 267.000000 0 0 1 484.434334 465.620715 L466.590901 445.758643 A240.300000 240.300000 0 0 0 508.485034 396.398226 z"/>
									<desc class="value">4.30%</desc>
									<desc class="x centered">499.386150374</desc>
									<desc class="y centered">431.134455077</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M484.434334 465.620715 A267.000000 267.000000 0 0 1 435.575624 500.450547 L422.618062 477.105492 A240.300000 240.300000 0 0 0 466.590901 445.758643 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">453.237168043</desc>
									<desc class="y centered">473.541857372</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M435.575624 500.450547 A267.000000 267.000000 0 0 1 296.982304 533.847674 L297.884074 507.162907 A240.300000 240.300000 0 0 0 422.618062 477.105492 z"/>
									<desc class="value">8.60%</desc>
									<desc class="x centered">365.421687749</desc>
									<desc class="y centered">513.591535794</desc>
								</g>
								<g class="big_slice">
									<path class="slice reactive tooltip-trigger" d="M508.485034 396.398226 A240.300000 240.300000 0 0 1 297.884074 507.162907 L306.000000 267.000000 A0.000000 0.000000 0 0 0 306.000000 267.000000 z"/>
									<desc class="value">16.49%</desc>
									<desc class="x centered">361.928617687</desc>
									<desc class="y centered">373.339137779</desc>
								</g>
							</g>
						</g>
						<g class="series serie-2 color-2">
							<g class="slices">
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">297.433188911</desc>
									<desc class="y centered">520.505290374</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">297.433188911</desc>
									<desc class="y centered">520.505290374</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">297.433188911</desc>
									<desc class="y centered">520.505290374</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M296.982304 533.847674 A267.000000 267.000000 0 0 1 226.070046 521.755181 L234.063042 496.279663 A240.300000 240.300000 0 0 0 297.884074 507.162907 z"/>
									<desc class="value">4.30%</desc>
									<desc class="x centered">263.361208175</desc>
									<desc class="y centered">517.040508582</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M226.070046 521.755181 A267.000000 267.000000 0 0 1 171.200283 497.473504 L184.680255 474.426154 A240.300000 240.300000 0 0 0 234.063042 496.279663 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">203.353355662</desc>
									<desc class="y centered">498.952557447</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M171.200283 497.473504 A267.000000 267.000000 0 0 1 71.823634 395.259229 L95.241271 382.433306 A240.300000 240.300000 0 0 0 184.680255 474.426154 z"/>
									<desc class="value">8.60%</desc>
									<desc class="x centered">124.135713463</desc>
									<desc class="y centered">443.815451198</desc>
								</g>
								<g class="big_slice">
									<path class="slice reactive tooltip-trigger" d="M297.884074 507.162907 A240.300000 240.300000 0 0 1 95.241271 382.433306 L306.000000 267.000000 A0.000000 0.000000 0 0 0 306.000000 267.000000 z"/>
									<desc class="value">16.49%</desc>
									<desc class="x centered">243.020048768</desc>
									<desc class="y centered">369.320810409</desc>
								</g>
							</g>
						</g>
						<g class="series serie-3 color-3">
							<g class="slices">
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">83.5324525822</desc>
									<desc class="y centered">388.846267263</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">83.5324525822</desc>
									<desc class="y centered">388.846267263</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">83.5324525822</desc>
									<desc class="y centered">388.846267263</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M71.823634 395.259229 A267.000000 267.000000 0 0 1 46.081921 328.086758 L72.073728 321.978082 A240.300000 240.300000 0 0 0 95.241271 382.433306 z"/>
									<desc class="value">4.30%</desc>
									<desc class="x centered">69.1461847776</desc>
									<desc class="y centered">357.766693862</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M46.081921 328.086758 A267.000000 267.000000 0 0 1 39.004232 268.503227 L65.703809 268.352905 A240.300000 240.300000 0 0 0 72.073728 321.978082 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">54.1207972519</desc>
									<desc class="y centered">296.919721305</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M39.004232 268.503227 A267.000000 267.000000 0 0 1 76.289079 130.904839 L99.260171 144.514355 A240.300000 240.300000 0 0 0 65.703809 268.352905 z"/>
									<desc class="value">8.60%</desc>
									<desc class="x centered">61.1786909966</desc>
									<desc class="y centered">200.661103734</desc>
								</g>
								<g class="big_slice">
									<path class="slice reactive tooltip-trigger" d="M95.241271 382.433306 A240.300000 240.300000 0 0 1 99.260171 144.514355 L306.000000 267.000000 A0.000000 0.000000 0 0 0 306.000000 267.000000 z"/>
									<desc class="value">16.49%</desc>
									<desc class="x centered">185.867137888</desc>
									<desc class="y centered">264.970728976</desc>
								</g>
							</g>
						</g>
						<g class="series serie-4 color-4">
							<g class="slices">
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">87.7746254543</desc>
									<desc class="y centered">137.709596627</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">87.7746254543</desc>
									<desc class="y centered">137.709596627</desc>
								</g>
								<g class="slice">
									<desc class="value">0.00%</desc>
									<desc class="x centered">87.7746254543</desc>
									<desc class="y centered">137.709596627</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M76.289079 130.904839 A267.000000 267.000000 0 0 1 120.959220 74.519067 L139.463298 93.767160 A240.300000 240.300000 0 0 0 99.260171 144.514355 z"/>
									<desc class="value">4.30%</desc>
									<desc class="x centered">107.180677805</desc>
									<desc class="y centered">109.4906364</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M120.959220 74.519067 A267.000000 267.000000 0 0 1 168.613708 38.058945 L182.352337 60.953050 A240.300000 240.300000 0 0 0 139.463298 93.767160 z"/>
									<desc class="value">3.58%</desc>
									<desc class="x centered">151.871058101</desc>
									<desc class="y centered">65.5487856353</desc>
								</g>
								<g class="slice">
									<path class="slice reactive tooltip-trigger" d="M168.613708 38.058945 A267.000000 267.000000 0 0 1 306.000000 0.000000 L306.000000 26.700000 A240.300000 240.300000 0 0 0 182.352337 60.953050 z"/>
									<desc class="value">8.60%</desc>
									<desc class="x centered">238.283795345</desc>
									<desc class="y centered">22.5560634273</desc>
								</g>
								<g class="big_slice">
									<path class="slice reactive tooltip-trigger" d="M99.260171 144.514355 A240.300000 240.300000 0 0 1 306.000000 26.700000 L306.000000 267.000000 A0.000000 0.000000 0 0 0 306.000000 267.000000 z"/>
									<desc class="value">16.49%</desc>
									<desc class="x centered">246.51177697</desc>
									<desc class="y centered">162.610470732</desc>
								</g>
							</g>
						</g>
					</g>
					<g class="titles">
						<text class="title plot_title" x="400.0" y="26">Candidate's work experience (in number of months)</text>
					</g>
					<g class="plot overlay" transform="translate(168, 46)">
						<g class="series serie-0 color-0"/>
						<g class="series serie-1 color-1"/>
						<g class="series serie-2 color-2"/>
						<g class="series serie-3 color-3"/>
						<g class="series serie-4 color-4"/>
					</g>
					<g class="plot text-overlay" transform="translate(168, 46)">
						<g class="series serie-0 color-0">
							<text class="centered" x="464.626232875" y="71.7372834417">7.17%</text>
							<text class="centered" x="545.784255169" y="186.951290388">10.75%</text>
							<text class="centered" x="539.653120776" y="368.381111667">5.38%</text>
							<text class="centered" x="411.379364566" y="211.950013753">34.05%</text>
						</g>
						<g class="series serie-1 color-1">
							<text class="centered" x="365.421687749" y="516.25820246">8.60%</text>
							<text class="centered" x="361.928617687" y="376.005804446">16.49%</text>
						</g>
						<g class="series serie-2 color-2">
							<text class="centered" x="124.135713463" y="446.482117865">8.60%</text>
							<text class="centered" x="243.020048768" y="371.987477076">16.49%</text>
						</g>
						<g class="series serie-3 color-3">
							<text class="centered" x="61.1786909966" y="203.3277704">8.60%</text>
							<text class="centered" x="185.867137888" y="267.637395643">16.49%</text>
						</g>
						<g class="series serie-4 color-4">
							<text class="centered" x="238.283795345" y="25.222730094">8.60%</text>
							<text class="centered" x="246.51177697" y="165.277137399">16.49%</text>
						</g>
					</g>
					<g class="plot tooltip-overlay" transform="translate(168, 46)">
						<g class="tooltip" style="opacity: 0" transform="translate(0 0)">
							<a>
								<rect class="tooltip-box" height="0" rx="0" ry="0" width="0"/>
								<text class="text">
									<tspan class="label"/>
									<tspan class="value"/>
								</text>
							</a>
						</g>
					</g>
					<g class="legends" transform="translate(10, 56)">
						<g class="legend reactive activate-serie" id="activate-serie-0">
							<rect class="color-0 reactive" height="12" width="12" x="0.0" y="1.0"/>
							<text x="17.0" y="11.2">Tooling and In…</text>
							<title>Tooling and Infrastructure</title>
						</g>
						<g class="legend reactive activate-serie" id="activate-serie-1">
							<rect class="color-1 reactive" height="12" width="12" x="0.0" y="22.0"/>
							<text x="17.0" y="32.2">Design Kit or …</text>
							<title>Design Kit or Component</title>
						</g>
						<g class="legend reactive activate-serie" id="activate-serie-2">
							<rect class="color-2 reactive" height="12" width="12" x="0.0" y="43.0"/>
							<text x="17.0" y="53.2">Product Develo…</text>
							<title>Product Development</title>
						</g>
						<g class="legend reactive activate-serie" id="activate-serie-3">
							<rect class="color-3 reactive" height="12" width="12" x="0.0" y="64.0"/>
							<text x="17.0" y="74.2">Documentation/…</text>
							<title>Documentation/Application Development</title>
						</g>
						<g class="legend reactive activate-serie" id="activate-serie-4">
							<rect class="color-4 reactive" height="12" width="12" x="0.0" y="85.0"/>
							<text x="17.0" y="95.2">Systems Develo…</text>
							<title>Systems Development</title>
						</g>
					</g>
					<g class="legends" transform="translate(790, 56)"/>
				</g>
			</svg>
			
		</figure>
	</body>
</html>

**Comment by paradoxxxzero** [comment]
It is now fixed
