### ISSUE TITLE
datey plots different offline and online

### ISSUE THREAD

**Issue by amunizp** [Kozea/pygal#174]
Might be the same for others:
When offline all the datapoint coordinates are put on the plot as labels.
When online the datapoint  coordinate labels are loaded and later are hidden untill pointer is near the point. The process seems to do first the tredline then the dots then the labels and finally the legend.

http://kozea.github.io/pygal.js/javascripts/svg.jquery.js:3973

Why does it need to go online? Why does it load the labels to later hide them?

And if I can sneak in another question: how many are too many datapoints? 16.5k seems like a lot for SVG, is there a way to remove at least some of the labels?

**Comment by amunizp** [comment]
Why does it need to go online? It seems to be looking for some CSS or something. Can it be with they data?

**Comment by paradoxxxzero** [comment]
Because by default the js and css files are served from github. This is just a shorthand to lower the svg size. Nothing prevents you to link those files from your local filesystem or from your own server. See: http://pygal.org/other_customizations/#idcustom-css-and-js
