### ISSUE TITLE
Anyway to plot multiple chart to single svg file

### ISSUE THREAD

**Issue by saravana815** [Kozea/pygal#177]
Hi, I have multiple sets of data. Each data set would be represented by a chart. 
Doing chart.render_to_file(file.svg) from different charts to same file creates a invalid xml file.

Is there any way to plot multiple charts to the same svg file?

**Comment by paradoxxxzero** [comment]
Currently, there's no way to do that but you could perhap's manually put them in one big svg file by nesting them. See http://www.w3.org/TR/SVG11/struct.html#SVGElement
