### ISSUE TITLE
Exception when rendering a graph with a range of integer as x_lables

### ISSUE THREAD

**Issue by genieplus** [Kozea/pygal#178]
If a range of integer is provided as x_lables, an expection is raised

    import pygal
    chart = pygal.Bar()
    chart.x_labels = range(1, 3)
    chart.add('sample', [1 , 5, 17])
    chart.render_to_file('sample.svg')
 
    TypeError: object of type 'int' has no len()

Full stack trace: https://gist.github.com/genieplus/9266a865444d2691e074

Is there any design restriction that makes the x_lables restricted to a list of string?

It would be nice if a chart can handle any iterable as x_labels ;)

**Comment by paradoxxxzero** [comment]
It might be nice to have auto cast, but you can just do a `map(str, range(1, 3))`.
