### ISSUE TITLE
Reusable/configurable charts?

### ISSUE THREAD

**Issue by JamesRamm** [Kozea/pygal#179]
I'd like to add/remove/modify data and appearance after a chart has been created...how to go about this is not mentioned in the docs, but it looks like I could edit either `.nodes`, and/or other properties in order to do this and then call render again....

It would be good to be able to do stuff like create a chart, then add a title to it, or change the appearance of a line, or modify the data etc etc...

Can anyone point me in the right direction towards doing this?

**Comment by blakev** [comment]
So you generate the chart, and you want to edit it afterwards -- correct? Are you wanting to make these changes in the Python code, or in some browser that's serving the chart, or by another program altogether?

Where do you want to make changes after it's been created?

**Comment by JamesRamm** [comment]
It could be in python code or 'browser'.
The idea is to embed the plot in a webkit widget within a Qt desktop application and provide the user controls to generate a chart and then alter the appearance etc.

So, the controls could trigger some python code to make the changes or it is possible to manipulate the DOM (through js etc..)

**Comment by blakev** [comment]
If you want to make the changes with Python, why wouldn't you just re-generate the chart? Or, use a library like `BeautifulSoup` to modify the output.. or even the CSS?

If you want to modify it in the browser, jQuery could change tag attributes; though there's probably one specifically designed for SVG data.

**Comment by paradoxxxzero** [comment]
For python edition you have the obscus http://www.pygal.org/en/latest/api/pygal.graph.public.html?highlight=add_xml#pygal.graph.public.PublicApi.add_xml_filter method and in javascript you can add a js to the `js` config.
