### ISSUE TITLE
Xlink attributes not applied to links in all cases

### ISSUE THREAD

**Issue by fvox13** [Kozea/pygal#18]
Create a simple pie chart and embed into an HTML page as an IFRAME:

``` python
graph = pygal.Pie()
graph.add("Low", [{'value': 10, 'xlink': {'href': '/foo/', 'target': '_top'}}])
graph.add("Medium", [{'value': 5, 'xlink': {'href': '/bar/', 'target': '_top'}}])
graph.add("High", [{'value': 15, 'xlink': {'href': '/baz/', 'target': '_top'}}])
```

The links will open in the parent window, but _only_ if you click the part of the pie slice that is not covered by the tooltip.
![missing_link_attributes](https://f.cloud.github.com/assets/847899/79182/4dd5ae7a-61a5-11e2-85ba-91d53bf9958a.gif)

**Comment by a-ssdv** [comment]
It seems the problem is actual. 
When I click any value-link on [docs page](http://www.pygal.org/en/stable/documentation/configuration/value.html#links) target page displays instead of the chart (unless I hold Ctrl button while clicking).
Legend-links work fine.
