### ISSUE TITLE
Candlestick or OHLC Charts?

### ISSUE THREAD

**Issue by greencoder** [Kozea/pygal#186]
I don't see anything in the docs for these charts. I'm happy to work on it myself, but I wanted to see if you knew of any work that had been done on these charts before I start?

**Comment by paradoxxxzero** [comment]
Indeed there's no candlestick as of now. The closest thing to it is the box plot : http://pygal.org/chart_types/#idbox-plot This could be a starting point.

**Comment by mrjbq7** [comment]
Hi @greencoder, I just noticed this issue and I don't mean to distract from this discussion or from pygal, but ``matplotlib`` has some support for candlesticks:

http://matplotlib.org/examples/pylab_examples/finance_demo.html

It also has some support (no idea how good) for outputting SVG.

**Comment by greencoder** [comment]
Thanks, @mrjbq7. I was hoping to use pygal because the examples are so beautiful. The Maplotlib examples I saw were pretty pedestrian, but it could be a good place for me to start.
