### ISSUE TITLE
include_x_axis=False

### ISSUE THREAD

**Issue by rob-bb** [Kozea/pygal#190]
Hi

I am trying to create svg xy graph, and I have removed every thing but the line, or at least tried to.

        xy_chart = pygal.XY(width=800, height=180, style=custom_style, show_legend = False,
                            show_y_labels=False, show_minor_x_labels=False,
                            show_x_guides=False, show_y_guides=False, interpolate='cubic', show_dots=False,
                            show_x_axis=False, include_x_axis=False, include_y_axis=False)

all looks good, I get a graph with the line only and one extra element I don't want. (this is missing the < and / > to make it show up).

g class="axis x" path class="line" d="M0.000000 0.000000 v120.000000"/ 

I had thought show_x_axis=False would prevent that.  Is this a bug or am I doing something wrong?

cheers,

**Comment by paradoxxxzero** [comment]
I added a `show_x_labels` option for this kind of use. (`include_y_axis` does not exist and `include_x_axis`  alters the scale not the display.)
This will be released in 1.6.3
