### ISSUE TITLE
Tooltip displaying 'None' for some data points in secondary Y-axis lines

### ISSUE THREAD

**Issue by sctchang** [Kozea/pygal#192]
So I have secondary Y-axis enabled (i.e. `pygal.add('SomeLabel', data_point, secondary=True)`) and some of the tooltips for certain data points are showing up as `None` when you hover over them.

I have `None`s in my data points, and by default `pygal` is supposed to ignore the None data points. While it is doing that correctly when it renders the line, it does seem to screw up the tooltips when `secondary=True` is set. This doesn't happen when I add data points with the default Y-axis setting.  Do you know what is going wrong here?

I had mistakenly submitted this [issue](https://github.com/s3rvac/pygal-toggle-graphs/issues/2) to s3rvac's fantastic [`pygal-toggle-graphs`](https://github.com/s3rvac/pygal-toggle-graphs) repository. His sharp eye pointed out that the bug actually resides within `pygal`, so I am resubmitting the issue here.

![hoverlabelnone2](https://cloud.githubusercontent.com/assets/606349/6173533/f410d988-b2a5-11e4-858e-98bf75dfb4ce.JPG)
![hoverlabelnone1](https://cloud.githubusercontent.com/assets/606349/6173539/f6ccd2b2-b2a5-11e4-8ab3-ca602997c52e.JPG)

**Comment by paradoxxxzero** [comment]
It's a bug indeed, it will be fixed in 1.6.3

**Comment by sctchang** [comment]
Thanks! Can't wait.
