### ISSUE TITLE
Lost hours/minute with DateY plots

### ISSUE THREAD

**Issue by biolds** [Kozea/pygal#193]
Using today's master, with python 2.7:
While plotting a DateY graph, it seems pygal loses the hours and minutes part of a datetime.datetime object passed to it.

The bug happens in pygal/graph/time.py, in the function date_to_datetime:
the datetime object matches the condition isinstance(x, date), and then the datetime.combine(x, time()) call removes the hours and minutes.

I don't understand what the call to combine() is supposed to do, or if the isinstance wasn't expected to match a datetime object. any hint how to fix this ?

(Pdb) bt
  /home/lds/tmp/stati.py(36)<module>()
-> datey.render_to_file('stat.svg')
  /home/lds/bin/pygal/pygal/ghost.py(165)render_to_file()
-> f.write(self.render(is_unicode=True, **kwargs))
  /home/lds/bin/pygal/pygal/ghost.py(122)render()
-> .make_instance(overrides=kwargs)
  /home/lds/bin/pygal/pygal/ghost.py(111)make_instance()
-> series = self.make_series(self.raw_series)
  /home/lds/bin/pygal/pygal/ghost.py(100)make_series()
-> return prepare_values(series, self.config, self.cls, offset)
  /home/lds/bin/pygal/pygal/util.py(412)prepare_values()
-> value = (x_adapter(value[0]), adapter(value[1]))
  /home/lds/bin/pygal/pygal/util.py(323)<lambda>()
-> fun = lambda *args, **kwargs: f(g(*args, **kwargs))
> /home/lds/bin/pygal/pygal/graph/time.py(37)date_to_datetime()
-> return datetime.combine(x, time())
(Pdb) print x
2015-01-12 11:37:00
(Pdb) print datetime.combine(x, time())
2015-01-12 00:00:00
(Pdb)

**Comment by paradoxxxzero** [comment]
What you want is nat a DateY (DateLine) but a DateTimeLine (https://github.com/Kozea/pygal/blob/master/pygal/graph/time.py#L52) which handles time too.

**Comment by biolds** [comment]
Well, as can be seen on the last line of this DateY and DateLine classes are the same:
# Old pygal compat
DateY = DateTimeLine

So the behaviour is the same.

**Comment by paradoxxxzero** [comment]
Oh sorry I misread your report, I'll investigate correctly as soon as I
can.

**Comment by biolds** [comment]
No problem. Thanks.

**Comment by ericpulvino** [comment]
I'm using the following configuration my memval and cpuval list is just tuples of (timestamp,values).

    memgraph = pygal.DateTimeLine(show_legend=False,title=unicode('Realtime Memory Consumption: '+proc_name), y_title='Bytes',x_label_rotation=rotation,no_data_text=mem_no_data_text)
    memgraph.x_labels = label_range
    memgraph.x_label_format = "%Y-%m-%d"
    memgraph.add('Data', memval)
    memgraph = memgraph.render()

    cpugraph = pygal.DateTimeLine(show_legend=False,title=unicode('Realtime CPU Consumption: '+proc_name), y_title='Percent',x_label_rotation=rotation,no_data_text=cpu_no_data_text)
    cpugraph.x_labels = label_range
    cpugraph.x_label_format = "%Y-%m-%d"
    cpugraph.add('Data', cpuval)
    cpugraph = cpugraph.render()

I am also seeing this issue. **ALSO Label Range format is not being applied as well as shown in pic**

![bad_timegraph](https://cloud.githubusercontent.com/assets/7875697/6922724/5d0e55fe-d79b-11e4-9469-a92af1991c85.png)

**Comment by ericpulvino** [comment]
Haha the CPU graph looks bizarre without the Hour/Minute data.
![bad_timegraph](https://cloud.githubusercontent.com/assets/7875697/6922924/88447fb8-d79c-11e4-9a16-89c9cdf60fd7.png)

**Comment by ericpulvino** [comment]
Haha the CPUgraph looks bizarre without the hour/minute data.
![bad_timegraph2](https://cloud.githubusercontent.com/assets/7875697/6922940/a33b620a-d79c-11e4-8f9a-20fa485ee684.png)

**Comment by paradoxxxzero** [comment]
Alright this is fixed.
As for `x_label_format` this is not a config property, this was a hack in datey.
Now use the standard `x_value_formatter` like this:
```python
    line.x_value_formatter = lambda x: x.strftime("%Y-%m-%d")
```
