### ISSUE TITLE
bubble chart and network chart

### ISSUE THREAD

**Issue by zen0x90** [Kozea/pygal#194]
Hi,

I'm trying pygal and it works fine for what I'm doing. But I'd like to use some charts like these ones :
 - Bubble Chart : http://bl.ocks.org/mbostock/4063269
 - Kind of network node chart : http://orgo.stolarsky.com/ (without animation)

Is it possible to do it with pygal ?

Cheers,

**Comment by blakev** [comment]
I don't believe PyGal is the charting library you're looking for with those examples.

I think these are more "client side" interactive graphs generated with [d3.js](http://d3js.org/)

**Comment by zen0x90** [comment]
Well, I'm not looking for someting interactive but I understand I need to use an another library for network chart and bubble (without chart).

Thanks
