### ISSUE TITLE
Map questions

### ISSUE THREAD

**Issue by ChrisYang** [Kozea/pygal#195]
1. How can I get map instance for other countries, like uk or China. 
I do see the note that ' As other country are implemented, this will be externalized in other packages. (Please submit pull requests :))' What the packages are ? 

2. Can we draw the map coordinate (using the latitude and longitude of an address ) in some how ?

**Comment by Brobin** [comment]
The only maps available right now are Switzerland and France. If you would like to make one for China or the UK, I believe they are accepting pull requests. I think they should all be put in a new package #225

**Comment by paradoxxxzero** [comment]
Okay they are now in separate package. To add a map, get an open source map of your country, clean it up to get the same scructure as the existing maps, adapt the python code. See https://github.com/Kozea/pygal_maps_fr/blob/master/pygal_maps_fr/maps.py
