### ISSUE TITLE
Firefox making twice requests per SVG file

### ISSUE THREAD

**Issue by h-2-0** [Kozea/pygal#196]
Hi!

I was wondering if someone knows or care to explain the following behaviour. 

I'm using Django to plot graphs based on SQL queries and display them in client's browsers. I configured Django to filesystem cache static and SVG files at server-side. Everything caches fine. But today I noticed that SVG files are hitting the server two times, with few seconds of difference, per file when using Firefox.  I have no problems using Opera (cache works perfectly). 

I am worried about this because I'm developing a webapp to let users plot tons of different types of graphs from tons from large databases.

FIRST CYCLE
Request header:
GET /mysvgfiles/15.svg HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-gb,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8000/svg/
Cookie: csrftoken=qzW; djdt=hide
Connection: keep-alive

Response:
<?xml version='1.0' encoding='utf-8'?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" .....
etc...

Cache:
Expires	Sun Feb 07 2106 07:28:15 GMT+0100 (BST)
Fetch Count	14
Last Fetched	Tue Mar 10 2015 16:18:39 GMT+0000 (GMT)
Last Modified	Thu Jan 01 1970 01:00:00 GMT+0100 (BST)

SECOND CYCLE:
Request header:
GET /mysvgfiles/15.svg HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-gb,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8000/svg/
Cookie: csrftoken=qzW; djdt=hide
Connection: keep-alive

Request response:
HTTP/1.0 200 OK
Date: Tue, 10 Mar 2015 16:18:37 GMT
Server: WSGIServer/0.2 Python/3.2.3
Last-Modified: Tue, 10 Mar 2015 15:16:45 GMT
Content-Length: 12192
Content-Type: image/svg+xml
X-Frame-Options: SAMEORIGIN

Response:
<?xml version='1.0' encoding='utf-8'?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" ...
etc

SVG
<svg id="chart-a347c80d-47dc-4cd0-b6ee-0265fc01f2dd" class="pygal-chart" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 70" width="80" height="70">
etc...

Cache:
Expires	Sun Feb 07 2106 07:28:15 GMT+0100 (BST)
Fetch Count	14
Last Fetched	Tue Mar 10 2015 16:18:39 GMT+0000 (GMT)
Last Modified	Thu Jan 01 1970 01:00:00 GMT+0100 (BST)

**Comment by h-2-0** [comment]
Perhaps the browser reads from socket the SVG file, realises it already downloaded the SVG file, stops the connection (at this point my Django runserver throws a "broken pipe" socket error 32 ), then server or browser retries GET again?

**Comment by paradoxxxzero** [comment]
I don't see anything in pygal that would trigger this. Maybe a bug in firefox ?

**Comment by h-2-0** [comment]
Perhaps. In any case thanks paradoxxxzero!

**Comment by paradoxxxzero** [comment]
Np, if you get more information on this, don't hesitate to reopen the issue.
