### ISSUE TITLE
error plotting maps in IPython 3 (jupyter)

### ISSUE THREAD

**Issue by elsoftwaredejuan** [Kozea/pygal#199]
Hi
I recently moved my environment to IPython 3 (Jupiter) and when I try to plot maps , doesn't work. I try also with the examples providing on the web but unfortunately with same results.

**Comment by luckydonald** [comment]
> doesn't work

This is a very specific description.
(In fact, it even lacks the pronoun at all..)

**Comment by elsoftwaredejuan** [comment]
Thankyou for your response!

It is so kind..... ;)

Try to run this example  http://pygal.org/chart_types/#idworldmap-charts on
IPython 3 (Jupiter)
It does not draw anything, the rest of examples (except map examples) works.

Regards

**Comment by luckydonald** [comment]
So you got a blank window? Or stacktraces with errors?

**Comment by paradoxxxzero** [comment]
Ok for some reason ipython does not support nested svg, but rather split them in 2 when adding the svg to the notebook.
This is an ipython bug imho.

**Comment by elsoftwaredejuan** [comment]
ok tks!
