### ISSUE TITLE
texts not displaying as monospace.

### ISSUE THREAD

**Issue by trvrm** [Kozea/pygal#200]
Texts on my charts are appearing using a serif font, rather than the expected default monospace font.

Further inspection indicates that base.css includes 

      font-family: "{{ style.font_family }}";

which typically renders as 

      font-family: "monospace";

However, it appears that Chrome and Firefox do not recognize this font family when it is quoted.
If we replace the above with:

    font-family: monospace;

we achieve the desired behaviour.

I suspect `style.font_family` should *only* be quoted if it contains spaces.  I can write a patch for this if it would help.

**Comment by dhaikney** [comment]
+1. Seeing exactly the same behaviour (safari / chrome). A patch would be good.

**Comment by luckydonald** [comment]
Also this seem to prevent the usage of 
```python
font_family="'Brush Script MT', monospace"
```   
which should translate to
```css
font-family: 'Brush Script MT', monospace
```

**Comment by luckydonald** [comment]
@paradoxxxzero  What is the search path for the font, when using render_png?
(Only slightly related here, but i dont want to open a new issue for this quick question...)
