### ISSUE TITLE
Minimum dot size for dot charts

### ISSUE THREAD

**Issue by micheleb** [Kozea/pygal#201]
It would be nice if `pygal.Dot` had an option to set the minimum radius for dots; small values currently become close to invisible as soon as a single very large value appears in the series.

**Comment by paradoxxxzero** [comment]
Hum, maybe making the logarithmic option work with dot will fix this issue.
Otherwise I don't really see how to add a minimal value without breaking the proportions (because 0 should still be invisible right ?).

**Comment by micheleb** [comment]
0 should be invisible indeed and yes, making dot radii logarithmic could help.

Ideally, having an option to "break" dots over a certain threshold like is done for column charts (see [this example][1]) would be great. I understand that it's kind of hard to visualize, and to implement, so logarithmic dots will do :) 

[1]: https://alesandrab.wordpress.com/2014/03/17/broken-column-and-bar-charts/
