### ISSUE TITLE
Linear interpolation not displayed anymore in firefox for svg generated under pygal 1.7

### ISSUE THREAD

**Issue by xguihot** [Kozea/pygal#202]
Just to notify that with version 1.7, since April 9, in Firefox (not in Chrome), display of cubic linear interpolations has disappeared in svg graphs. Going back to an earlier version solved the problem.

**Comment by longsonr** [comment]
pygal should set stroke-dasharray to none rather than 0,0 if it doesn't want dashed strokes.
