### ISSUE TITLE
Would be possible to set different range for two y axes?

### ISSUE THREAD

**Issue by zhangang15** [Kozea/pygal#203]
Hi, my problem requires two y axes, left one for data number while another one for percentage, the range of left one is fine(0-1000), but the current range for percentage one is from 0.00-35.00, because the numbers are in this range. When I set the "pygal.Line(range=(0.00, 100.00))", both of y axes are changed to (0.00-100.00), I cannot find how to solve this in documents, so would it be possible to set the range of y axes separately. Thank you. I am looking forward your help.

**Comment by paradoxxxzero** [comment]
You have a `secondary_range` option now :)
