### ISSUE TITLE
Document Box 

### ISSUE THREAD

**Issue by lu-zero** [Kozea/pygal#208]
It is not documented what each parameter means.

**Comment by blakev** [comment]
What do you mean? Which object/method are you talking about?

**Comment by lu-zero** [comment]
I was assuming [Box](http://pygal.org/chart_types/#idbox-plot) would have a mean to take parameters directly instead of calculating them out of the samples, not sure why.

**Comment by paradoxxxzero** [comment]
It is now documented: http://www.pygal.org/en/latest/documentation/types/box.html
