### ISSUE TITLE
Lines aren't displayed at Mozilla Firefox

### ISSUE THREAD

**Issue by ya-888** [Kozea/pygal#210]
Hi all!
Lines are not displayed at Mozilla Firefox for some chart types.
You can see it if open this link http://pygal.org/chart_types/#idline-charts by Mozilla Firefox and Chrome(for example) and compare chart representations.

Best regards and thanks for cool charting library!

**Comment by paradoxxxzero** [comment]
Thanks, I've got to release 2.0 soon now :)
