### ISSUE TITLE
Black screen on rendered svg file

### ISSUE THREAD

**Issue by amk91** [Kozea/pygal#211]
If I open in the browser the svg file of a chart I make it shows a black screen.
But if I do a CRTL+A I can see the text and, when I use the mouse, I can see the values of the bars.
I'm using the examples on the website.

This is the image of the problem: http://i.imgur.com/2bJS7Ni.png

**Comment by paradoxxxzero** [comment]
Which pygal version ? Which browser ?

**Comment by amk91** [comment]
I installed pygal with pip, so I think the 1.7. I'm working on Windows 8.1 and using Chrome. I made tests with Firefox and IE too

**Comment by hinerk** [comment]
I solve the same problem by installing tinycss and cssselect packages.

**Comment by kirill-krokodil** [comment]
encountering the same problem: windows7, 3.4.3 python, 1.7 pygal, firefox, chrome.
yesterday it rendered well, today - render black picture.

maybe pygal authors help or at least confirm if i should install some other packages, like @hinerk told?
thank you.

**Comment by paradoxxxzero** [comment]
tinycss and cssselect are for png generation with cairosvg.

If the svg does not show in the browser it is another problem, is there any error in the console ?

**Comment by kirill-krokodil** [comment]
Yes, found error:
16:50:12.929 Method getPreventDefault() is outdated. For its replacement use method defaultPrevented.1 svg.jquery.js:3287:0

**Comment by paradoxxxzero** [comment]
Interesting could you please try with git version it may already be fixed.

Le mar. 21 juil. 2015 15:58, kirill-krokodil <notifications@github.com> a
écrit :

**Comment by kirill-krokodil** [comment]
@paradoxxxzero you right, in version 1.9.9 there is no such a problem with black screen.
thank you!

**Comment by paradoxxxzero** [comment]
You are welcome. Version 2.0 will be out shortly!
