### ISSUE TITLE
datey graph problems

### ISSUE THREAD

**Issue by nagesh2425** [Kozea/pygal#213]
Hi,

I am very new to python as well as using pygal. I am currently using pygal to plot some graphs for my internal application. Can anyone Please help me on the following questions?

In my application am using "datey" to plot my graph. Can anyone tell me that how can i do the following things to look my graph more better:

1. Currently am passing only date values to x-axis but it is also displaying some default time. I have used "datey.x_label_format = "%Y-%m-%d" which is not woked. Even i have used truncate_label option which is working fine but at the end of the date it is displaying some dots. How can we remove those dots?

2. How can we pass some explicit values to y-axis?

3. Is there any option to mention the scale values for both x and y axis? Because in x-axis it is scaling 2 days and for some point 3 days which looks very odd.

**Comment by paradoxxxzero** [comment]
See http://www.pygal.org/en/latest/documentation/types/xy.html#dates
