### ISSUE TITLE
Formatting x_labels in a DateY chart doesn't work

### ISSUE THREAD

**Issue by hoffmaan** [Kozea/pygal#220]
I'm trying to use my own list of datetime objects as x_labels in a DateY chart. I'm using excactly the code from the second example in http://pygal.org/chart_types/#iddatey (except that I use render_to_png() instead of render()) but I get a different result (see image). The differences are:

- the x-axis has four labels instead of three
- the x values do not correspond to the values I give in datey.x_labels
- the x_values' format does not correspond to what I define in datey.x_label_format

Is this a known problem? Is there a solution or workaround for it? Am I overlooking something?

System: RHEL 6.6, Python 2.6.6, Pygal 1.7.0

Any help extremely welcome.

Thanks and regards,
Andreas

![datey](https://cloud.githubusercontent.com/assets/11486917/8034603/646cafec-0de9-11e5-9e55-4c5280291eae.png)

**Comment by vernondcole** [comment]
me, too.
Using Python 3.4, Ubuntu 15.04, Pygal 1.7.0, render_to_file

**Comment by paradoxxxzero** [comment]
DateY har been replaced with DateTimeLine, DateLine, TimeLine, TimeDeltaLine which are now equivalent to XY charts (both axis uses dynamic scales).
If you just want to plot a line with date as x_labels use a Line with formated date as x_labels.

Version 2.0 is comming soon with hopefully an updated documentation and some fixes for datelines.
 (`x_label_format` was not a config option and was removed, use `x_value_formatter` instead)

**Comment by paradoxxxzero** [comment]
Check the doc at http://pygal.readthedocs.org/en/latest/documentation/types/xy.html#dates
