### ISSUE TITLE
XY graph with variable point size

### ISSUE THREAD

**Issue by bkmeneguello** [Kozea/pygal#223]
Allow three elements tuples in XY series with the third value being a multiplier of default point size (or 1 when only two elements provided).

**Comment by paradoxxxzero** [comment]
It is possible now in the git version.
```python
  chart.add('serie', [
            {'color': 'red', 'value': 1, 'node': {'r': 12}},
            {'color': 'red', 'value': 2, 'node': {'r': 26}},
  ])
```
