### ISSUE TITLE
Undefined variable from import

### ISSUE THREAD

**Issue by satishvad** [Kozea/pygal#224]
I installed pygal using pip install. 

import pygal
bar_chart= pygal.Bar()

I get an error at this point "Undefined variable from import: Bar"

Any help is appreciated.

Thank you

**Comment by paradoxxxzero** [comment]
Something is really wrong with your install.

**Comment by satishvad** [comment]
Thank you paradoxxxzero. I have uninstalled and re-installed pygal using pip install. There was no error during installation though. 

Any advise?

**Comment by paradoxxxzero** [comment]
Which OS / python version are you using ?
What does `repr(pygal)` give you ?
