### ISSUE TITLE
Maybe there is a better way to handle the maps

### ISSUE THREAD

**Issue by Brobin** [Kozea/pygal#225]
One issue I have with the country maps is that as many countries are added, this code base will become very large and unorganized. I propose that the maps be moved to a separate package (maybe called pygal-map), or at least into a sub-folder of `graph`. This would allow development of new country maps separately from the core of pygal.

I personally have been working on an US map and have been tinkering around with some project structures. I was thinking something like this.

```
|-pygal_map
    |- ch
        - __init__.py
        - ch.cantons.svg
    |- fr
        - __init__.py
        - fr.departements.svg
        - fr.regions.svg
    |- us
        - __init__.py
        - us.states.svg
    - __init__.py
    - base.py
    - world.py
    - worldmap.svg
```

Then to add a new map, you simply create the folder for the country, include the svg and the map class and reference it in `pygal_map/__init__.py`.

I would be willing to take the lead on this or reorganize it in the existing repository if you think this is something that would be beneficial.

I also noticed that the hover on the maps is very slow. Is there anything we can do to fix this or is this due to the nature of the svg?

**Comment by cleder** [comment]
-> http://kartograph.org/

**Comment by paradoxxxzero** [comment]
My take on this is that maps should be in separate packages. Like pygal_maps_fr, pygal_maps_us,  pygal_maps_moon, each adding into pygal.maps namespace. Map makers will be responsible for their own packages. I'll try to externalize fr and ch as part of the 2.0.0 update.

**Comment by Brobin** [comment]
Sounds good. I agree that they should be in separate packages, so one doesn't need to download tens of maps to use one.

**Comment by HughP** [comment]
@Brobin Where did that USA map go to and can it be accessed from pygal? Did it have sub-districts to the state, county, or township level?

**Comment by Brobin** [comment]
I don't think anyone pulled the USA map out into a separate package. Frankly, this was 2 years ago and I'm not really active in this project much.

**Comment by sgzFalcon** [comment]
@HughP Did you find out where are the other maps? Is there any other way to use more maps in pygal?

**Comment by HughP** [comment]
@sgzFalcon No I did not find a solution to this. There are other datasets out there. For instance OSM has all countries and 2 level admin units which can be extracted. It would be really nice if these could be added to pygal. It would really push the utility of pygal forward.
