### ISSUE TITLE
Solutions for pyinstaller?

### ISSUE THREAD

**Issue by fountao** [Kozea/pygal#227]
Hi,
I really like pygal! However, due to complex hidden imports and resource files. It seems pyinstaller does not support pygal. Would anyone be kind to provide me solutions to solve this issue? Or will the developers consider to support pyinstaller?
Thank you!

**Comment by never-eat-yellow-snow** [comment]
This pull request (https://github.com/Kozea/pygal/pull/217) addresses the most important issue (the resource files with .svg and .css type). Feel free to try the fork at 

https://github.com/never-eat-yellow-snow/pygal

I have added a PyInstaller hook for pygal here in the comment section: https://github.com/Kozea/pygal/issues/182

It is labelled as py2exe, but in fact it is a pyinstaller hook :)

**Comment by fountao** [comment]
@never-eat-yellow-snow, thank you for your kind help! The hook codes work perfectly!
