### ISSUE TITLE
Is there a way to draw a 'best fit' line over a scatter plot

### ISSUE THREAD

**Issue by moormanm** [Kozea/pygal#228]
Hi all,

First let me say thank you for developing and sharing such an easy to use and clean visualization tool!

I have a requirement to produce a a 'scatter plot' type graph with an overlay of a best fit line. Is there any way to accomplish this in pygal? An example of what I am trying to do is here:

![image](https://cloud.githubusercontent.com/assets/5134378/8207269/45869976-14ce-11e5-899b-fdaadd2bbbe8.png)

I apologize if this is already documented somewhere. So far I have successfully created the scatterplot using the XY graph with stroke=False. 

Thanks!

**Comment by paradoxxxzero** [comment]
This would be a nice feature to have, this is related to implementing multi chart type in the same chart.
As of now you can manually add your line to the svg after rendering but it's a little inconvenient.
This could be implemented as a new chart type inheriting XY.

**Comment by paradoxxxzero** [comment]
You can now use something like that: http://pygal.readthedocs.org/en/latest/documentation/configuration/serie.html#stroke
