### ISSUE TITLE
Non linear axis values

### ISSUE THREAD

**Issue by nik000** [Kozea/pygal#230]
Hello,

I didnt find any way yet to be able to have non linear data on one axis.

For example I have the following data :
[75, 10, 2, 0.5, 0.1, 0.01]

If I display that, then 0.5, 0.1, 0.001 will be very close to one another and also basically all seem equal to 0 :(
If the axis could be set to some logarithmic computations, then we could be able to see real differences between 0.1 and 0.01

Is that already possible ?
If not, that would be a great feature I think.

Anyway, thanks for pygal, I discovered that very recently and it's really neat.

Best regards,
 nik0

**Comment by zoloedov** [comment]
Try "logarithmic" key.

```python
line = pygal.Line(logarithmic=True)`
line.title = 'My non linear data'
line.add('line1', [ 0.01, 0.1, 1, 10, 100, 1000])
line.render_to_file('logarithmic.svg')

**Comment by nik000** [comment]
Awesome, thanks a lot.
I knew I must have missed something, seemed like a basic feature for such module.
