### ISSUE TITLE
Why kozea.github.io must try to be accessed when browser loading an svg generated by pygal?

### ISSUE THREAD

**Issue by losemyheaven** [Kozea/pygal#231]
Hi all:

First, I should sincerely say thanks to every developer who build this convinient tools!

I found that each time I use Chrome to open a svg file generated by pygal, the browser will try to access kozea.github.io. Due to my poor network condition, this procedure makes it so slow to show an svg that it will cost up to 30 secs!

What should I do to solve this problem?

**Comment by paradoxxxzero** [comment]
You're welcome !
For your problem, see https://github.com/Kozea/pygal/issues/174#issuecomment-70627748

**Comment by losemyheaven** [comment]
Thank U~~~~
