### ISSUE TITLE
Sparkline Axes Labels

### ISSUE THREAD

**Issue by peterstory** [Kozea/pygal#239]
Currently, axes are disabled by default for sparklines. If they are enabled, they display in an unreadable format:
![bad labels](https://cloud.githubusercontent.com/assets/1322135/8574472/d65519ea-2564-11e5-8df1-1cfd570c6641.png)

It would be much better if abbreviated axes labels were displayed instead. The sunspot example on Edward Tufte's website provides a good example of how this might look:
<http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR>
![sunspots](https://cloud.githubusercontent.com/assets/1322135/8574538/2e61a630-2565-11e5-91fe-307e88273919.png)

**Comment by paradoxxxzero** [comment]
Agreed, might be possible by just tweaking some options to hide guides and
set labels to min and max.
