### ISSUE TITLE
Extending y_labels past the data point values

### ISSUE THREAD

**Issue by AlexKhodaverdian** [Kozea/pygal#241]
So I've noticed that pygal graphs values based on the maximum and minimum data points, ie the y_labels will only go from 8 to 32 if I have Min = 10, Max = 30. Is there any way to manually extend this 8 to 0?

**Comment by AlexKhodaverdian** [comment]
https://github.com/Kozea/pygal/issues/119
Take a look at this if you're confused

**Comment by paradoxxxzero** [comment]
http://pygal.readthedocs.org/en/latest/documentation/configuration/axis.html#include-x-axis ?
