### ISSUE TITLE
When all data points are 0, show a line with all 0's rather than no data graph

### ISSUE THREAD

**Issue by AlexKhodaverdian** [Kozea/pygal#244]
Is this possible? I've noticed if I pass [0,....,0] in for data, it automatically defaults to a no data graph

**Comment by paradoxxxzero** [comment]
Yup it's been fixed in git and will be with v 2.0

Le mar. 21 juil. 2015 19:34, AlexKhodaverdian <notifications@github.com> a
écrit :

**Comment by AlexKhodaverdian** [comment]
Thank you :)
