### ISSUE TITLE
Radar chart - axis scaling, range, negative values

### ISSUE THREAD

**Issue by fafnir1990** [Kozea/pygal#245]
Hello
I am writting to explain about x_axis scaling.
Is that possible to use different axes for data in one radar chart with pygal?
My plot is very unclear when one value is grater than for example 100 but others are lower than 3.
And is that possible tu use range from -5 to 5?

Thank you in advance

**Comment by paradoxxxzero** [comment]
| Is that possible to use different axes for data in one radar chart with pygal?
No

| one value is grater than for example 100 but others are lower than 3.
You can try the logarithmic option but obviously you can't have a clear graph with very different values.

| And is that possible tu use range from -5 to 5?
Radar is positive values only (how would you represent negative values ?). You can set the range with tthe range option though.
