### ISSUE TITLE
Add Link to legend element.

### ISSUE THREAD

**Issue by mklauber** [Kozea/pygal#246]
I would like to be able to set a url representing the source data for each series as a url.  I'd then like the legend text to be a link to the specified url

Looking at it, looks like I would need to add a `link` Key to the `SerieConfig` class, and then in the `pygal/graph/graph.py` file, update `def _legend` to check the existence of that key, and if it exists, create a `<a xlink:href="...">...</a>` surrounding the `rect`, `text` and `title` elements.  I'm working on a PR for this, trying to determine how to implement it.

The one issue I could use some advice on is how to determine what the `link` element is on a given series.  From what I can determine, the `def _legends` (note: not `_legend`) code returns just the legend text, not the series itself.

**Comment by paradoxxxzero** [comment]
For legends are you looking for this http://pygal.readthedocs.org/en/latest/documentation/configuration/value.html#legend ?
For the series, the links are per-value. Just wrap your values with a dict containing the link.

**Comment by mklauber** [comment]
Thanks.

**Comment by mklauber** [comment]
I was looking at documentation at http://pygal.org/documentation/ and I didn't find that.  Is pygal.readthedocs.org the official source of documentation, and should pygal.org be updated?

**Comment by paradoxxxzero** [comment]
pygal.readthedocs.org is the new doc for the still unreleased v2. As soon as v2 is out pygal.org will point to readthedocs.org

**Comment by mklauber** [comment]
Thanks.  Appreciate the clarification.
