### ISSUE TITLE
Radar chart - point labels, metadata in png

### ISSUE THREAD

**Issue by fafnir1990** [Kozea/pygal#247]
Hello
I have  more quenstions:

1) How can I display metadata in png file? I used a dictionnary to put the values and labels and there are visible in svg, but not in png.

2) I scaled my values for clarify my radar chart. Is it possible to change displayed scaled values into old values?

Thanks in advance

**Comment by paradoxxxzero** [comment]
1) you can print values using ``print_values`` but you can't as of now print labels.
2) Sorry I don't see what you mean

**Comment by fafnir1990** [comment]
2) I had a problem with radar chart: I need to present data with drastically different ranges (for example 100 - 500 and 1-3). That makes my chart is very unclear. I scaled my values (all of them are from 0 to 1), but I wolud like to display older values on my chart. Is it possible?

**Comment by paradoxxxzero** [comment]
You can try this http://www.pygal.org/en/latest/documentation/configuration/label.html#y-labels (Second chart)

**Comment by fafnir1990** [comment]
Nope, unfortunately it doesn` work, because in each axe should be another scale.
I find another problem: parameter:
 'show_y_labels=False' 
for radar chart doesn`t work.

**Comment by paradoxxxzero** [comment]
Every option should now work with radar.

Test:

``` python
        radar = Radar()
        for i in range(10):
            radar.add(str(i), [i * j for j in range(8)])
        radar.x_labels = range(8)
        radar.x_label_rotation = 35
        radar.y_label_rotation = 35
        radar.y_labels = [{
            'label': '500',
            'value': 10
        }, {
            'label': '1000',
            'value': 20
        }, {
            'label': '5000',
            'value': 30
        }, {
            'label': '10000',
            'value': 40
        }]
```

**Comment by fafnir1990** [comment]
This scripts crash, after adding any render function after for loop...
but that construction of dictionary works in my last chart. Two last questions:
1) How to remove numbers from y axis in radar chart
2) How to modify whole data serie (for example I would like to thick line 'Lipinski':
        radar_chart.add(Real, prop_val)
        radar_chart.add('Lipinski', scaled_val)
  prop_val & scaled_val are lists of floats.

**Comment by paradoxxxzero** [comment]
It crashes with the latest git version ? If it does for you would you mind pasting the stacktrace.

1) Set the labels to '' if you don't want them to show
2) If you want a thicker line for serie see http://www.pygal.org/en/latest/documentation/configuration/serie.html#stroke-style

**Comment by fafnir1990** [comment]
I`m sorry, after update it works.|
Thank you very much
