### ISSUE TITLE
Point`s labels aren`t displayed after render_to_file()

### ISSUE THREAD

**Issue by fafnir1990** [Kozea/pygal#252]
Hello 
I used a code from website:

import pygal
chart = pygal.Bar(print_labels=True)
chart.add('line', [
  0,
  {'value': 12, 'label': 'Twelve'},
  31,
  {'value': 8, 'label': 'eight'},
  28,
  0
])
chart.render_to_file('bar.svg')

I open it in firefox, but labels are invisible. 
How can I resolve that?
Thanks in advance.

**Comment by paradoxxxzero** [comment]
I can't reproduce. Do you have the last pygal version installed ?

**Comment by fafnir1990** [comment]
I`m sorry, you are updating so quickly... Yes, I have 2.0.1 and all is correct.
