### ISSUE TITLE
Filled linechart not getting darker on mouse hover

### ISSUE THREAD

**Issue by amitt001** [Kozea/pygal#253]
On updating the svg+xml pygal graph using js function in every 10 seconds when mose is hovered over the linechart the area of linechart doesn't become darker. Also graph points doesn't show their value

**Comment by paradoxxxzero** [comment]
If you load a new svg in your page directly you have to call the initialization function of pygal.js: https://github.com/Kozea/pygal.js/blob/gh-pages/coffee/pygal-tooltips.coffee#L255
