### ISSUE TITLE
bug with render_in_browser

### ISSUE THREAD

**Issue by waixwong** [Kozea/pygal#266]
Hi there, 

Thanks for making pygal, it is super cool. I recently discovered a bug in the render_in_browser() function in public.py.

public.py, line83  kwargs.setdefault('force_uri_protocol', 'https') 
The line above was added on Jul 17

Adding this line causes the render_in_browser() function unable to work. self.render_tree() function takes no arguments, but In line 84, kwargs is passed into this function, which leads to a TypeError:render_tree() got an unexpected keyword argument 'force_uri_protocol'

**Comment by paradoxxxzero** [comment]
Thanks for reporting!
