### ISSUE TITLE
Unused code?

### ISSUE THREAD

**Issue by Xender** [Kozea/pygal#267]
Hi.

Are things like `Serie` class being used anywhere?

I am new to this codebase and it looks pretty much like orphaned historical arfifact to me.
If so, could they it pruned? (And possibly other dead code it there is any.)

//EDIT (now I see, `prepare_values` is clearly being used, please ignore me mentioning it at first).

**Comment by paradoxxxzero** [comment]
Yes Serie is still used here https://github.com/Kozea/pygal/blob/05e9f3ddc79e613fe0b501f47eecfcb27fb020df/pygal/graph/base.py#L171 in `prepare_values` as a placeholder for specific serie data.
