### ISSUE TITLE
.render_in_browser() leads to: TypeError: render_tree() got an unexpected keyword argument 'force_uri_protocol'

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [Kozea/pygal#268]
import pygal as pg
import pandas as pd
firm = pd.read_csv('panel_firm.csv')
firm.columns
line_chart = pygal.Line()
import pygal
line_chart = pygal.Line()
line_chart.add('money', firm['money']
)
line_chart.render_in_browser()

In [12]: line_chart.render_in_browser()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-92469ca2bccb> in <module>()
----> 1 line_chart.render_in_browser()

/usr/local/lib/python2.7/dist-packages/pygal/graph/public.pyc in render_in_browser(self, **kwargs)
     83             raise ImportError('You must install lxml to use render in browser')
     84         kwargs.setdefault('force_uri_protocol', 'https')
---> 85         open_in_browser(self.render_tree(**kwargs), encoding='utf-8')
     86 
     87     def render_response(self, **kwargs):

TypeError: render_tree() got an unexpected keyword argument 'force_uri_protocol'

**Comment by jrkerns** [comment]
Just downloaded and also got the same error.

**Comment by paradoxxxzero** [comment]
This will be fixed in 2.0.7 I am releasing.
