### ISSUE TITLE
Question about a large number of series and sidebar behavior

### ISSUE THREAD

**Issue by Resisty** [Kozea/pygal#269]
Hello,

I'm sorry for making this an issue but I'm unaware of other places to ask questions. I have a project wherein I make dynamic pygal SVGs with an arbitrary number of series. Anything over about 26 series gets truncated. 

Example: http://i.imgur.com/Yvemllz.png
There are about 140+ (I think, the bars get pretty tiny :P) bars there and some people I work with would like the entire list.

I'm not sure if there's something I can do in the python code or if this is solvable with javascript, but any advice is very much appreciated. Thanks!

**Comment by paradoxxxzero** [comment]
You can change the chart width (in python to have a large graph) and use an `overflow: auto` to the dom container to add a scrollbar for instance.

**Comment by Resisty** [comment]
Hello,

The width isn't the issue; the bars are all present and working correctly. It's the sidebar's list of series names. `overflow: auto` or `scroll`, etc, doesn't seem to have any effect on the surrounding div.

**Comment by paradoxxxzero** [comment]
You can try putting the legend at the bottom, scroll is not possible on svg element as far as I know.
Or you know you can hide the legend and generate it in html.

**Comment by Resisty** [comment]
> scroll is not possible on svg element

Ah, I'll just have to figure out some kind of ajaxy goodness then. Thanks!
