### ISSUE TITLE
tooltip_font_size undefined?

### ISSUE THREAD

**Issue by cageowner** [Kozea/pygal#276]
Hi There,

Firstly - love the library, easily the most intuitive i have come across so far.

So far my implementation mostly works, the svg renders on my page as I would expect, I can set a custom style and configure the axes etc. The issue comes with hovering.

When I hover, the bars highlight as expected, but the tooltip does not show. The browser in developer mode returned an error as follows:

<img width="601" alt="screenshot 2015-10-22 13 31 39" src="https://cloud.githubusercontent.com/assets/15241115/10655548/45673228-78c1-11e5-84a2-2b453d623e2b.png">

When I download and open the JS file with my IDE, it also seems to suggest the tooltip_font_size is an "unresolved variable". (learning Javascript is on my to-do list....).

I have tried to remedy this by setting the 'tooltip_font_size' variable in a custom style configuration, but it doesn't seem to work.

Anyway, apologies if this is a repeat or I have overlooked something here. I would appreciate any help.

Cheers,
Owen

**Comment by paradoxxxzero** [comment]
It seems like you have the 2.0.x version of pygal with a 1.x version of pygal.
Try with the 2.0.x version  of pygal and the corresponding js https://github.com/Kozea/pygal.js/blob/gh-pages/2.0.x/pygal-tooltips.js
It should work!

**Comment by cageowner** [comment]
Works perfect.

Cheers!
