### ISSUE TITLE
Set axis to use integers only

### ISSUE THREAD

**Issue by harleyjcooper** [Kozea/pygal#289]
I have two axes made entirely of integers. I know I can use `value_formatter`, but when the secondary range is, say, range(0,8), it will generate lines like 0, 0.667, 1.333, 2.000 - if I use the `value_formatter` with something, the best I can do is something like `lambda x: '' if x - int(x) != 0 else str(int(x))`. That's all well and good, but it gives a graph where the bar with value 1 sits in between 0.667 and 1.333.

Can't there be an `integers=True` flag? And make that configurable for secondary as well?

**Comment by paradoxxxzero** [comment]
It's normal to have floats, the second scale must fit in the first. You can try the `secondary_range` option and find a multiple range that make the division round.
