### ISSUE TITLE
2.1.0 cause apache mod_wsgi infinite loop during import

### ISSUE THREAD

**Issue by razerraz** [Kozea/pygal#294]
I regret to have nothing to show as debug trace, simply because my system give me nothing except a gateway timeout even with debug mode everywhere...

The only thing I have after 7 hours lost investigating why my django project was not working anymore after system upgrate are symptoms for conditions below :
I run a django instance via apache mod_wsgi, calling somewhere a "view" (django term) with import pygal in there, nothing else. The host is ARMv7 beaglebone running archlinux.
The thing is working fine with pygal 2.0.12, failing with 2.1.0 with absolutly no logs and exception running import command. State seems to be something looping indefinitly until timeout is reached by apache caller process
The thing is always working when using standalone django server
The thing is always working when using the python django shell
The charts composing is fine for the 2 last conditions

I'm a little confused with this, with no clue or ideas. 
The only thing I'm sure, after downgrading all upgraded packages and upgrade one by one until a failure occurs, is that pygal 2.1.0 is the cause.

After so much time investigating every corner of my installation, cannot pass without reporting this here

Thanks for support

PS : I'm using pygal for my graph generation of datas from IOT, and I'm quite happy with it and have to thank and congrats for the job done, real great stuff...

**Comment by paradoxxxzero** [comment]
Hello, sorry to hear about this.

I doubt this is the new version that create the infinite loop since as you can see there is not so much differences between the two versions (https://github.com/Kozea/pygal/compare/2.0.12...2.1.0) except creating a module `stats.py`.

One thing new that I see is I made a wheel package for this release maybe this can cause some problems (not too sure about that).

Can you give me more informations just in case like the python version.

**Comment by paradoxxxzero** [comment]
Just out of curiosity do you have scipy installed ?

**Comment by liZe** [comment]
Someone reported a hanging application using mod_wsgi and scipy (with a solution to fix the problem):
https://mail.scipy.org/pipermail/scipy-user/2011-November/031014.html

**Comment by paradoxxxzero** [comment]
That's problematic. If you don't use it remove scipy in the meantime I'll make a subrelease of pygal trying to import scipy only if there's a need for it.

**Comment by liZe** [comment]
Related mod_wsgi documentation, explaining why modules playing with the GIL need a special configuration: http://code.google.com/p/modwsgi/wiki/ApplicationIssues#Python_Simplified_GIL_State_API

**Comment by razerraz** [comment]
I had scipy installed, remove it and seems working with 2.1.0, at least not looping...
Scipy was upgraded as well yesterday : 0.16.0 -> 0.16.1. Minor release...
No deps relative to scipy on my system -> was it in pygal hard deps previously ? I don't see what else depending on it and force the install...
Congrats for founding cause of all this mess

**Comment by razerraz** [comment]
http://code.google.com/p/modwsgi/wiki/ApplicationIssues#Python_Simplified_GIL_State_API

Very usefull link
I understand now what the mecanism behind my problem
Thx

**Comment by paradoxxxzero** [comment]
Scipy was a dep in an early version of pygal, but that was a long time ago. Glad it works for you now.

**Comment by razerraz** [comment]
I began using it a year ago, but never mind, I understand now why I had dead loop reading the liZe link and can prevent other potential similar cases with mod_wsgi.
In other world I've not spend 7 hours for nothing
Chears

**Comment by razerraz** [comment]
I start using it 1 year ago, but never mind. I understand now why I face dead loop, reading liZe link, and can diagnose other potential similar cases breaking mod-wsgi
In other word I've not spend 7 hours on this thing for nothing ;)
Chears

**Comment by razerraz** [comment]
Last thing
I take a look at your patch and I am in doubt
At one stage or another, the problem will occur nevertheless, with nothing to investigate but a dead loop...
The cause is a mod_php limitation that can be solved in general cases by a simple settings options, details in link above. I'm just sceptic about this option, since it is a celery task that use pygal and not the wsgi process...
It is not pygal related.  
Q&A or Warning section of pygal documentation about that should be a better patch imho.

**Comment by paradoxxxzero** [comment]
Yes you are right.
(The patch was a quick and dirty one to avoid regression since now it could only happens using the new code)

For me the best solution would be to remove scipy soft dependency entirely and there's 2 options about that:
 - removing the stats part (leaving the user totally in charge of confidence intervals computations)
 - reimplementing the missing function which is not a simple task (http://eprints.maths.ox.ac.uk/184/1/tdist.pdf)
