### ISSUE TITLE
tooltips doesn't work on non-firefox browsers

### ISSUE THREAD

**Issue by eplaut** [Kozea/pygal#299]
using the `http://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.js` or `http://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js` (with pygal lib)

when I use local file (and the script is inline, it works)

tried on:
chromium - linux
safari and chrome - osx
chrome - windows

**Comment by paradoxxxzero** [comment]
Are you accessing svg files from file:// ? In this case use `force_uri_protocol`

**Comment by AndreCL** [comment]
I followed the instructions here: http://www.blog.pythonlibrary.org/2015/04/16/using-pygal-graphs-in-flask/
Have the same issue. Works on Firefox (windows), doesn't work on IE or chrome (windows)

**Comment by paradoxxxzero** [comment]
This site is outdated, see http://pygal.readthedocs.io/en/latest/documentation/web.html#directly-in-the-html

**Comment by DmonteiroD** [comment]
same issue here. 
Not working in chrome.Version 49.0.2623.110 (64-bit) debian

Any solution available?
