### ISSUE TITLE
Timezone info in XY DateTime charts

### ISSUE THREAD

**Issue by geo-petrini** [Kozea/pygal#302]
I have a XY DateTime chart where I made sure to add tz to each date in the x axis.
```
import pytz
datetz = pytz.timezone('Europe/Zurich').localize(date)
```

but the labels on the chart are without timezone.
If I use this formatter
`config.x_value_formatter = lambda dt: dt.strftime('%Y-%m-%d %H:%M:%S / %Z%z')`

labels are printed just as 

> 2016-01-21 22:00:09 /

Additionally each label is wrong by 2 hours (1 for the timezone, 1 for the daylight saving time).
So the label above should be
> 2016-01-22 00:00:09 /
This applies also to the tooltips

If I don't apply the timezone and use the offset is of 1 hour (because Europe/Zurich is on GMT+1)

On the other hand timestamp is printed correctly in the title
`config.title = 'Chart Title \n %s / %s' % (min_timestamp, max_timestamp)`
produces

> Chart Title
> 2016-01-22 00:00:09+01:00 / 2016-01-22 16:16:25+01:00

Is there a way to display them correctly?
Thanks

**Comment by paradoxxxzero** [comment]
If you want to display timezone aware datetimes, you have to set the display timezone:

```python
line.x_value_formatter = lambda x: (
            x.replace(tzinfo=timezone.utc).astimezone(tz)).isoformat()
```

**Comment by geo-petrini** [comment]
Sorry if I reopen this after so much time but I still have some difficulties handling the timezone issue.

I have this datetime: 2016-04-22 00:00:16
during "data preparation" I convert the naive date into a timezone aware datetime
```
self.tz = pytz.timezone(pytz.country_timezones('ch')[0])

timestamp = self.tz.localize(timestamp)
```

then I set the label formatter as you suggested

`config.x_value_formatter = lambda x: (x.replace(tzinfo=timezone('utc')).astimezone(self.tz)).isoformat()`


Upon rendering the label is printed as 
2016-04-21T23:00:16+02:00

If I don't use timezone aware datetimes the label is simply "2016-04-21 21:00:16" because pygal uses UTF.

What I want is the label to be printed as "2016-04-22 00:00:16".
Otherwise the alternative is to use an XY chart, with timestamps converted as numbers.. correct?

Thanks
