### ISSUE TITLE
Is it possible to avoid getting 'Warning Unresponsive script' when rendering +100 sparklines graphs in one page?

### ISSUE THREAD

**Issue by h-2-0** [Kozea/pygal#312]
Hi, 

Newbie here (especially when it comes to javascript) so please be patient. 

I'm sorry if my problem has a very obvious answer or isn't an issue at all but for the life of me I don't understand the mechanics of this.
**Problem**

I'm using Django 1.8 and Pygal version 1.6.1. Everything seems all right so far however whenever I try to render a dynamic HTML page with more than 100 sparkline charts  for the first time (i.e. before caching) I get some 'Warning Unresponsive script' in my Iceweasel (Firefox) browser asking me to either continue or stop the script. The script usually stops in some line in some line in svg.jquery.js 

**Questions**

I noticed every little single sparkline chart calls the svg.jquery.js file from http://kozea.github.io/pygal.js/javascripts/ and thus slows down the rendering of the requested page even though my server has already finished its job. Is that how it works? Is it supposed to be doing this for each file? Or do I have to have the svg.jquery.js file on my server to make it run faster? Wouldn't be better to just call the file one time, cache it, and then call it? But is it a best practice? What is the best practice? Or what I need to do to accelerate the rendering process? 

This is how I prepare the chart to be later rendered in a template

    sparkline_chart = pygal.Line(no_data_text='') 
    sparkline_chart.style = custom_LightColorizedStyle
    sparkline_chart.add('', daily_data)
    sparkline_chart.render_sparkline(width=80,height=70)`
    sparkline_render_result = str(sparkline_chart.render())
    
    # I add to a dictionary the result 
    dict_sparks[str(item)+'_sold'] = sparkline_render_result[2:][:-1][44:]
    # Then I return the dictionary for further processing 
    return dict_sparks

After further processing this is  how I render in my template:

    {% for rows in extra_data %}
        <tr>
            <td>{{rows.sparkline_svg_code|safe}}</td>

**Comment by paradoxxxzero** [comment]
Three things:
  - If you can use pygal 2, pygal 1 has a very overweight js.
 - Sparklines don't use js so you can disable it with `sparkline_chart.js = ()` (I made it the default in master)
  - If it were regular charts, as you said you are better off hosting the js yourself and using this rendering method to load the js once: http://pygal.readthedocs.io/en/latest/documentation/web.html#directly-in-the-html

**Comment by h-2-0** [comment]
I don't recall at the moment why I had to stick to pygal 1. I guess I just need to disable the JS then! :+1:)
Thank you, paradoxxxzero!
