### ISSUE TITLE
Value label positioning in bar charts is off-centered

### ISSUE THREAD

**Issue by andtrott** [Kozea/pygal#315]
Heyo!
<img width="542" alt="screen shot 2016-04-07 at 2 41 08 pm" src="https://cloud.githubusercontent.com/assets/9217492/14367774/cbe13ef2-fcce-11e5-9f30-3aa6efd64a42.png">

I just built and installed the current version (2.1.1) of pygal using a clone of the repo, and horizontal positioning of the bar graph seems off. See attached image. For some reason, if I install pygal through pip (still apparently version 2.1.1), the positioning still seems correct. Any idea what's going on here?

Cheers,
Andrew

**Comment by paradoxxxzero** [comment]
Thanks for the report
