### ISSUE TITLE
Setting style opacity just change it in the legend box

### ISSUE THREAD

**Issue by Leprosy** [Kozea/pygal#321]
I'm rendering a plot with several data sets(> 20) so I want to use a custom style that makes any line except the one that is being inspected(by hovering over the line or in the legend box with the mouse) more transparent. But when I set the opacity, only the opacity of the color on the legend box is changed. The lines retain the default opacity.

I'm using this code to set the opacity:

```python
            style = LightenStyle('#336676', step=5)
            style.opacity = ".2"
            plot = pygal.Line(config, style=style)
```
`config` is just a pygal config object

Here is a screenshot, left one is with the style "change", right one is with LightenStyle unchanged.

![screenshot - 270516 - 16 29 34](https://cloud.githubusercontent.com/assets/851905/15620468/c7b08174-2430-11e6-9127-535fe9931281.png)

PS: The lines differ because with every render the data is generated randomly, but I think you get the idea.

**Comment by Leprosy** [comment]
Is this in the 2.2.3 version? I've upgraded but seems the fix isn't there

**Comment by paradoxxxzero** [comment]
Yes, I added an extra style option so you would have to write:
```
            style = LightenStyle('#336676', step=5)
            style.opacity = ".2"
            style.stroke_opacity = ".2"
            plot = pygal.Line(config, style=style)
```

**Comment by Leprosy** [comment]
Hey...works amazing. Awesome!
