### ISSUE TITLE
Cannot add unlabeled lines to Line class

### ISSUE THREAD

**Issue by dmwesterhoff** [Kozea/pygal#323]
I am trying to do exactly the same code as in the docs:

chart = pygal.Line()
chart.add([1, 2, 3], fill=True)	

and It returns the error:
TypeError: add() takes exactly 3 arguments (2 given)

-----------------------------------------------

My desired functionality is to be able to add a list of lists all under the same 'label', am I missing something?

**Comment by dmwesterhoff** [comment]
Also to add this is what I tried originally:

line_chart = pygal.Line()
for line in lines:
    line_chart.add('dave', line)

This adds all lines in different color and assumes that all labels are a unique 'dave' entry resulting in many different colors of lines drawn and a massive legend in my case.

**Comment by paradoxxxzero** [comment]
This was a typo in the doc, nevertheless I added a new API in which the title is facultative.
