### ISSUE TITLE
Improper rendering of PNG images

### ISSUE THREAD

**Issue by sachinkamath** [Kozea/pygal#327]
Hi,
 When I generate PNG using pygal (using `graph_obj.render_to_png(fname)`), the output renders for a donut chart with multiple values, but fails to render properly when only value is inserted and looks something like this : 

![dhanesh95_main](https://cloud.githubusercontent.com/assets/9546091/16015310/b614849e-31b2-11e6-8c8b-d52fc536816f.png)

It is a donut chart with only value in it, as you see. the SVG renders fine. I also noticed that there is no legend on any of the PNG's generated. 

Some useful info : 

Pygal Version : 2.2.3
Cairo SVG Version : 1.0.20

**Comment by liZe** [comment]
@sachinkamath Could you please provide the code you used to generate this example?

**Comment by sachinkamath** [comment]
@liZe : https://github.com/sachinkamath/fedstats-gsoc/blob/develop/output.py#L42

**Comment by liZe** [comment]
Thanks for the code. It's a bug in CairoSVG: Kozea/CairoSVG#111.

**Comment by sachinkamath** [comment]
@liZe Glad I could be of help. 

>  I also noticed that there is no legend on any of the PNG's generated. 

Any solution for this?

**Comment by liZe** [comment]
> Any solution for this?

Is there usually a legend (other than the square + name on the left) on donut PNGs?

**Comment by sachinkamath** [comment]
@liZe 
 
I was wondering if I can get the hover-percentages that are displayed when hovered over SVG's onto PNG rendered images somehow.

**Comment by liZe** [comment]
> I was wondering if I can get the hover-percentages that are displayed when hovered over SVG's onto PNG rendered images somehow.

It was possible in previous versions to get the values displayed, but it was a mess and had been removed. It's now added in JS. Maybe @paradoxxxzero has a solution that I don't know for you.

By the way, I've fixed the bug in CairoSVG. I'll release a new version soon.

**Comment by sachinkamath** [comment]
Thanks a lot for the fix. You guys are awesome :))

**Comment by paradoxxxzero** [comment]
You may be interested by this
http://pygal.readthedocs.io/en/stable/documentation/configuration/data.html#print-values

Le dim. 7 août 2016 16:36, Sachin Kamath <notifications@github.com> a
écrit :

**Comment by sachinkamath** [comment]
Just what I wanted. Thanks a lot.

You guys just became awesome-er ;)

**Comment by liZe** [comment]
:smile:.
