### ISSUE TITLE
truncate_label results in random characters

### ISSUE THREAD

**Issue by tmfwhovamber** [Kozea/pygal#330]
Not sure why, but when I truncate a label, it results in some weird characters added after the number of allowed characters.
In this example, I have used $dateline = pygal.Line(truncate_label=5) 
and have received this:
![screen shot 2016-07-12 at 3 04 56 pm](https://cloud.githubusercontent.com/assets/11076085/16779868/1124b80e-4842-11e6-8ecb-6bb69b7df70c.png)

**Comment by paradoxxxzero** [comment]
This is because when a label is truncated this unicode character: `…` is added at the end.
It seems like you are trying to display an utf-8 svg in an other encoding.
