### ISSUE TITLE
Tooltip/toggle selection doesn't work in chrome when using render()

### ISSUE THREAD

**Issue by DmonteiroD** [Kozea/pygal#331]
Example: https://jsfiddle.net/sqyetz46/

this only occurs when I do:

`chart=pie_chart.render()`

With render_to_file everything works fine.

`chart=pie_chart.render_to_file('test.svg')`

As far as I can see the svg output doesn't work properly inside an html file.

Another demo: https://jsfiddle.net/jf1sfnc7/

**Comment by paradoxxxzero** [comment]
You are trying to put an inline svg in a html page, you have to include the javascript in the html context:
http://pygal.readthedocs.io/en/stable/documentation/web.html#directly-in-the-html
