### ISSUE TITLE
Documentation for custom style is wrong

### ISSUE THREAD

**Issue by maxbellec** [Kozea/pygal#336]
On the page [http://www.pygal.org/en/stable/documentation/custom_styles.html](http://www.pygal.org/en/stable/documentation/custom_styles.html), the python code example at the bottom of the page is wrong: the custom css is not added at all.

The import on the first line is not useful (should be removed), and the line `config.css.append(custom_css_file)` should be replaced by `config.css.append("file://" + custom_css_file) `.

This solution works, at least for my pygal==2.2.3

**Comment by paradoxxxzero** [comment]
Thanks for the report. I forgot to update the documentation.
