### ISSUE TITLE
changing googlefonts makes no difference

### ISSUE THREAD

**Issue by dbwrangler** [Kozea/pygal#384]
Hi 

Loving pygal so far.

Changing to google fonts as per http://www.pygal.org/en/stable/documentation/custom_styles.html, I found it made no difference to my charts until I added to my html template:

    <style>
    @import url('https://fonts.googleapis.com/css?family=Indie+Flower|Dosis:700|Amatic+SC:700|Exo:600i|Fresca|Roboto|Raleway:700');
    </style>

Perhaps the docs could be updated to include this?

Thanks!

**Comment by paradoxxxzero** [comment]
Do you include the raw svg in html? Because in this case the processing instruction which include the stylesheet won't be there. You are right I will update the doc.
