### ISSUE TITLE
No option for tooltips without internet connection

### ISSUE THREAD

**Issue by blakeinate** [Kozea/pygal#394]
Is this something that will be added in the future? It seems like an issue for entities wanting to maintain a secure local network.

**Comment by skarone** [comment]
This is easy to do, just download the pygal.js, then:

bar_chart = pygal.Bar()
bar_chart.js = ['file:///localPygal.js/2.0.x/pygal-tooltips.min.ks']
bar_chart.render.....

**Comment by blakeinate** [comment]
Wow, thanks! I'm surprised I was unable to find this.
