### ISSUE TITLE
Stacked charts should have an option to render based on value in addition to percentage

### ISSUE THREAD

**Issue by aerianis** [Kozea/pygal#410]
Currently, the stacked charts (eg: StackedBar) render as 100% percent range stacked charts. 

There should be an option to render based on their stacked values in that one can specify if the chart should render based on 100% percent range (current), or actual values.

Here's a stacked bar chart based on values as an example:
http://study.com/cimages/multimages/16/image_stacked_bar_chart_resized.jpg

**Comment by szymag** [comment]
Hi @aerianis ,
> Currently, the stacked charts (eg: StackedBar) render as 100% percent range stacked charts.

Are you sure? You can put as bar's argument any numbers you want:
I'm able to reproduce your example:
```python
import pygal
line_chart = pygal.StackedBar()

line_chart.x_labels = ['Drums', 'Trombane', 'Trumpet', 'Tubs']
line_chart.add('Boys',  [2, 5, 3, 1])
line_chart.add('Girls', [1, 3, 4, 1])

line_chart.render_to_png('example.png')
```
which produce following graph:
![er](https://user-images.githubusercontent.com/11030008/33518209-823fb36a-d791-11e7-9fef-38cd295b8f86.png)
Only difference is that `pygal` don't create empty space above bars.

**Comment by aerianis** [comment]
Hi @szymag,

I think you're right. I copied and pasted the sample data from the 'basic
chart', the 1st one, and didn't notice that the data was in percentage
despite it being called out:
http://pygal.org/en/stable/documentation/types/bar.html#stacked

Thaks for responding, I'll close the issue.

Cheers.
