### ISSUE TITLE
Charts in Wordpress

### ISSUE THREAD

**Issue by mmBs** [Kozea/pygal#453]
Hi, is there any option to show interactive charts safely in Wordpress? I load svgs to Wordpress using 3rd party plugins (WP SVG images or Safe SVG) and they are displayed as normal pngs - without any animation.  
Do you have any solution for that? I will be really grateful.
Thanks.

**Comment by mmBs** [comment]
I solved my issue :) I believe it should be closed.

**Comment by Alberto-o** [comment]
Hi @mmBs ! I'm struggling with the same problem here. I can upload svg's to wordpress, but I cannot find the way for the mouseovers to show. How did you solve the issue?

**Comment by mmBs** [comment]
Hi @Alberto-o. To be honest it was a workaround, but I was fine with it. If I used pygal charts on my blog, I just opened them in the new tab. When you add svg in wordpress as a resource (or image) there is an option to open in a new tab.
