### ISSUE TITLE
world map has circles on it

### ISSUE THREAD

**Issue by jonsnow1357** [Kozea/pygal#473]
The world map has 4 circles around Italy ..

This can be seen even on the project page (http://www.pygal.org/en/stable/documentation/types/maps/pygal_maps_world.html) if you zoom in.

There must be a reason why, but I think it would be better if there were no circles ...

**Comment by jonsnow1357** [comment]
The world map has 4 circles around Italy ..

This can be seen even on the project page (http://www.pygal.org/en/stable/documentation/types/maps/pygal_maps_world.html) if you zoom in.

There must be a reason why, but I think it would be better if there were no circles ...

**Comment by paradoxxxzero** [comment]
These circles are San Marino, Malta, Liechtenstein and Luxembourg.

**Comment by jonsnow1357** [comment]
well, first of all sorry for the duplicate :(
Thanks for the explanation ... but just curious, why not Vatican too?

**Comment by paradoxxxzero** [comment]
This map is a cleaned version of the wikipedia blank map at the time it was made. So no idea...
