### ISSUE TITLE
Python 3.10 compatibility issues - ImportError: cannot import name 'Iterable' from 'collections' 

### ISSUE THREAD

**Issue by StevenMapes** [Kozea/pygal#514]
The _compat.py file needs to be updated to make it compatible with [Python 3.10](https://docs.python.org/3.10/library/collections.abc.html#collections.abc.Iterable)

An ImportError will be raised as ```collections.Iterable``` will be in ```collections.abc.Iterable```

**Comment by tirkarthi** [comment]
Seems to have been fixed in https://github.com/Kozea/pygal/commit/7796f14c80fe82b9435cdc33b7d2939c8331d649

**Comment by tirkarthi** [comment]
Reported also in https://github.com/Kozea/pygal/issues/500

**Comment by StevenMapes** [comment]
Thanks @tirkarthi I missed that issue
