### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs

### ISSUE THREAD

**Issue by cristianoccazinsp** [Kozea/pygal#521]
pygal/_compat.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working

Please release a minor update to resolve this warning/error.

**Comment by gentooboontoo** [comment]
Release 3.0.0 should fix the problem.

**Comment by cristianoccazinsp** [comment]
@gentooboontoo can we get an updated changelog for 3.0.0 as well?

**Comment by gentooboontoo** [comment]
[Docs](https://www.pygal.org/en/stable/changelog.html) has been rebuilt. The changelog is now up to date.
