### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections' in Python 3.10

### ISSUE THREAD

**Issue by jason990420** [Kozea/pygal#524]
Platform
- WIN10
- Python 3.10
- Pygal 2.4.0

Line 23 in _compat.py, 
```python
from collections import Iterable
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and **in 3.10 it will stop working**

It looks _compat.py already updated in 
https://github.com/Kozea/pygal/blob/master/pygal/_compat.py
https://github.com/Kozea/pygal/commit/7796f14c80fe82b9435cdc33b7d2939c8331d649

but not updated in version 2.4.0 on pypi.

**Comment by gentooboontoo** [comment]
New release 3.0.0 should fix the problem. Tell me if that's not the case.
