### ISSUE TITLE
Legend Positioning

### ISSUE THREAD

**Issue by cleder** [Kozea/pygal#56]
In the past Legends were placed right of the chart, now they are placed left.
Legends can be placed below the chart also.

To make this more flexible I suggest a 'legend_position' with the values 'right' 'bottom' 'left' and maybe 'top' (defaults to 'left'). 'legend_position' == None will not display the legend.  If a graph has secondary legends 'left' and 'right' are ignored (or maybe 'right' could be used to to invert the primary and secondary legends)

instead of the 'show_legend' and 'legend_at_bottom'

**Comment by SpainTrain** [comment]
Why was this closed?  Was this implemented?
