### ISSUE TITLE
Armenian (unicode)  characters

### ISSUE THREAD

**Issue by hanumanum** [Kozea/pygal#83]
Hi, how can I make this work

import pygal
line_chart = pygal.Line()
line_chart.title = 'մարդ'
line_chart.x_labels = map(str, range(2002, 2013))
line_chart.add('Վերնագիր', [None, None, 0, 16.6,   25,   31, 36.4, 45.5, 46.3, 42.8, 37.1])
line_chart.render_to_file('wikichart.svg')

I have seen following error
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by LukasSliacky** [comment]
Hi guys,

i don't know why, but i use python3 and when i have code:
bar.title = ('Kŕdeľ ďatľov učí koňa žrať kôru')

i see output:
K\xc5\x95de\xc4\xbe \xc4\x8fat\xc4\xbeov u\xc4\x8d\xc3\xad ko\xc5\x88a \xc5\xbera\xc5\xa5 k\xc3\xb4ru

in all others texts works encoding of my language normally.

Thanks for answer.
