### ISSUE TITLE
JS blocked on SSL sites

### ISSUE THREAD

**Issue by krikunts** [Kozea/pygal#87]
In your default config svg.jquery.js and pygal-tooltip.js are loaded via http.
This behavior leads to an error: most browsers block http content when using SSL on the site.
Maybe you should add some boolean setting like USE_SSL or somewhat to handle this.

**Comment by dbwrangler** [comment]
Hi - hover no longer works for me when I save js files locally. What I do in my html is:

    <script type="text/javascript" src="svg.jquery.js"></script>
    <script type="text/javascript" src="pygal-tooltips.min.js"></script>

I need a solution as I will deploy to Heroku. For now I'm embedding the js directly into the html which works. I have a flask app and have tried to save the files local to the html file.
