### ISSUE TITLE
RFE hide all line but the one hovered over

### ISSUE THREAD

**Issue by pypingou** [Kozea/pygal#94]
When the svg generated contains a number of categories, it would be nice to have an option to hide all of them but one.

I am thinking in such a graph: http://thisweekinfedora.org/assets/evolution.svg

So maybe add checkbox in the legend, or just add an option when building the graph to hide all lines but the active one (hovered over with the mouse).

Thanks for this great library though :)

**Comment by paradoxxxzero** [comment]
It is now also possible on legend box click.
